[package]
name = "physpanel"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies.windows]
version = "0.62"
features = [
    "Win32_Foundation",
]

[dependencies.windows-core]
version = ">=0.62.1"

[build-dependencies.windows-bindgen]
version = "0.64"